# Generated by Django 5.0.4 on 2024-05-01 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Nachricht')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlicht')),
                ('creates', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2, verbose_name='Zustand')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blg_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx')],
            },
        ),
    ]
